#!/usr/bin/env python
import sys
from NekonisiTwitterApi import NekonisiTwitterApi

def main():
    """main"""
    ntp = NekonisiTwitterApi()
    ntp.auto_unfollow()

if __name__ == '__main__':
    main()